import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author jerli
 */
public class AdminPage extends javax.swing.JFrame {
    
    Connection con;
    private crudUser CrudUser;
    private String userID;  // Declare userID as a field

   
   public AdminPage(String userID) {
        this.userID = userID;  // Set the userID after login
        initComponents();
    }
   
  

    public javax.swing.JTextField getSearchData() {
        return searchData;
    }

    public AdminPage(crudUser CrudUser) {
        this.CrudUser = CrudUser;
        initComponents();
    }

    /**
     * Creates new form UserPage
     */
    public AdminPage() {
        initComponents();
        
        
        
        String Url, User, Pass;
        Url = "jdbc:MYSQL://localhost:3306/water";
        User = "root";
        Pass = "";
        
        try{
            con = DriverManager.getConnection(Url, User, Pass);
        }catch(Exception e){
            System.out.println("Error!" + e.getLocalizedMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        useradmin = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbUsers = new javax.swing.JTable();
        addbtn = new javax.swing.JButton();
        updatebtn = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();
        requestbtn = new javax.swing.JButton();
        recordbtn = new javax.swing.JButton();
        searchData = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        announcebtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1094, 806));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logosmall.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        useradmin.setBackground(new java.awt.Color(102, 204, 255));
        useradmin.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        useradmin.setText("Users");
        useradmin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        useradmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useradminActionPerformed(evt);
            }
        });
        jPanel1.add(useradmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, 100, 40));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logout.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 20, -1, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/waterdrop3.png"))); // NOI18N
        jLabel2.setToolTipText("");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 470, -1, -1));

        tbUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "FullName", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbUsers);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 930, 340));

        addbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add.png"))); // NOI18N
        addbtn.setBorder(null);
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });
        jPanel1.add(addbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 170, -1, -1));

        updatebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/update.png"))); // NOI18N
        updatebtn.setBorder(null);
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });
        jPanel1.add(updatebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 170, -1, -1));

        deletebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete.png"))); // NOI18N
        deletebtn.setBorder(null);
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });
        jPanel1.add(deletebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 170, -1, -1));

        requestbtn.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        requestbtn.setText("Request");
        requestbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        requestbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestbtnActionPerformed(evt);
            }
        });
        jPanel1.add(requestbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 30, 100, 40));

        recordbtn.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        recordbtn.setText("Records");
        recordbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        recordbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recordbtnActionPerformed(evt);
            }
        });
        jPanel1.add(recordbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, 100, 40));

        searchData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchDataActionPerformed(evt);
            }
        });
        jPanel1.add(searchData, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 440, 40));

        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search.png"))); // NOI18N
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jPanel1.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 150, -1, -1));

        announcebtn.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        announcebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/announcement.png"))); // NOI18N
        announcebtn.setBorder(null);
        announcebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                announcebtnActionPerformed(evt);
            }
        });
        jPanel1.add(announcebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 30, 50, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void useradminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useradminActionPerformed

        // TODO add your handling code here:
        String sql = "SELECT * FROM user";
        try{
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            DefaultTableModel model = (DefaultTableModel)tbUsers.getModel();
            model.setRowCount(0);
            while(rs.next()){
                model.addRow(new String[]{rs.getString(1),rs.getString(4),rs.getString(3)} );
                
            }
        }catch(Exception e){
            System.out.println("Error!" + e.getLocalizedMessage());
        }
        
    }//GEN-LAST:event_useradminActionPerformed

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        // TODO add your handling code here:
        
        try {
        // Check if a row is selected in the table
        int selectedRow = tbUsers.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(new JFrame(), "Please select a user from the table.", 
                                          "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Get the ID from the selected row
        String ID = tbUsers.getValueAt(selectedRow, 0).toString(); // Assuming ID is in column 0
        
        Class.forName("com.mysql.cj.jdbc.Driver");
        String url = "jdbc:mysql://localhost:3306/water";
        String user = "root";
        String pass = "";
        
        Connection con = DriverManager.getConnection(url, user, pass);
        String sql = "DELETE FROM user WHERE userID = ?";
        
        // Use PreparedStatement to execute the query
        PreparedStatement pst = con.prepareStatement(sql);
        pst.setString(1, ID);
        int rowsAffected = pst.executeUpdate();
        
        if (rowsAffected > 0) {
            // Remove the row from the table model
            ((DefaultTableModel) tbUsers.getModel()).removeRow(selectedRow);
            JOptionPane.showMessageDialog(new JFrame(), "User deleted successfully.", 
                                          "Success", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(new JFrame(), "Invalid ID.", 
                                          "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        con.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(new JFrame(), "Error: " + e.getMessage(), 
                                      "Error", JOptionPane.ERROR_MESSAGE);
    }
        
    }//GEN-LAST:event_deletebtnActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        LogIn LoginFrame = new LogIn();
        LoginFrame.setVisible(true);
        LoginFrame.pack();
        LoginFrame.setLocationRelativeTo(null); 
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
        // TODO add your handling code here:
        
        crudUser crudUserFrame = new crudUser();
        crudUserFrame.setVisible(true);
        crudUserFrame.pack();
        crudUserFrame.setLocationRelativeTo(null); 
        this.dispose();

    }//GEN-LAST:event_addbtnActionPerformed

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
    
        // TODO add your handling code here:
        
    // Check if a row is selected in the table
    int selectedRow = tbUsers.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(new JFrame(), "Please select a user from the table.", 
                                      "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    // Get the selected user's data (ID, Fullname, Email, Username, Password, etc.)
    String userID = tbUsers.getValueAt(selectedRow, 0).toString(); // Assuming ID is in column 0
    String fullName = tbUsers.getValueAt(selectedRow, 1).toString(); // Full name in column 1
    String email = tbUsers.getValueAt(selectedRow, 2).toString(); // Email in column 2
    
    
    // Pass the data to the crudUser form for updating
    crudUser crudUserFrame = new crudUser(userID, fullName, email);
    crudUserFrame.setVisible(true);
    crudUserFrame.pack();
    crudUserFrame.setLocationRelativeTo(null); 
    this.dispose();  // Close the current AdminPage window
        
    }//GEN-LAST:event_updatebtnActionPerformed

    private void requestbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestbtnActionPerformed
        // TODO add your handling code here:
        RequestAdmin RequestAdminFrame = new RequestAdmin(); // Pass userID
        RequestAdminFrame.setVisible(true);
        RequestAdminFrame.pack();
        RequestAdminFrame.setLocationRelativeTo(null);
        this.dispose();
        
    }//GEN-LAST:event_requestbtnActionPerformed

    private void recordbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recordbtnActionPerformed
        // TODO add your handling code here:
        
        AdminRecords1 AdminRecords1Frame = new AdminRecords1();
        AdminRecords1Frame.setVisible(true);
        AdminRecords1Frame.pack();
        AdminRecords1Frame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_recordbtnActionPerformed

    private void searchDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchDataActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_searchDataActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        
        String ID = searchData.getText().trim();
        int notFound = 0;

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");

            String Url = "jdbc:mysql://localhost:3306/water";
            String User = "root";
            String Pass = "";

            Connection con = DriverManager.getConnection(Url, User, Pass);
            Statement st = con.createStatement();

            if (ID.isEmpty()) {
                JOptionPane.showMessageDialog(new JFrame(), "Search field is required", "Dialog",
                        JOptionPane.ERROR_MESSAGE);
            } else {
                // Dynamically build the SQL query
                String sql;
                if (ID.matches("\\d+")) { // Check if the input is numeric (likely an ID)
                    sql = "SELECT * FROM user WHERE userID = " + ID;
                } else {
                    sql = "SELECT * FROM user WHERE fullname LIKE '%" + ID + "%' OR username LIKE '%" + ID + "%'";
                }

                ResultSet rs = st.executeQuery(sql);

                if (rs.next()) {
                    // Create or access an instance of crudUser
                    crudUser crud = new crudUser();

                    // Use the getter methods to set the values in crudUser's text fields
                    crud.getFname().setText(rs.getString("fullname"));
                    crud.getEmailAddress().setText(rs.getString("email"));
                    crud.getUname().setText(rs.getString("username"));
//                    crud.getPass().setText(rs.getString("password"));
//                    crud.getConPass().setText(rs.getString("confirm_password"));

                    notFound = 1;

                    // Optionally, display the crudUser window if it isn't already visible
                    crud.setVisible(true);

                    con.close();
                }
                if (notFound == 0) {
                    JOptionPane.showMessageDialog(new JFrame(), "No matching record found", "Dialog",
                            JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (Exception e) {
            System.out.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_searchActionPerformed

    private void announcebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_announcebtnActionPerformed
     Announcements AnnouncementsFrame = new Announcements();
     AnnouncementsFrame.setVisible(true);
     AnnouncementsFrame.pack();
     AnnouncementsFrame.setLocationRelativeTo(null);
     this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_announcebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbtn;
    private javax.swing.JButton announcebtn;
    private javax.swing.JButton deletebtn;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton recordbtn;
    private javax.swing.JButton requestbtn;
    private javax.swing.JButton search;
    private javax.swing.JTextField searchData;
    private javax.swing.JTable tbUsers;
    private javax.swing.JButton updatebtn;
    private javax.swing.JButton useradmin;
    // End of variables declaration//GEN-END:variables
}
