import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author jerli
 */
public class AdminRecords1 extends javax.swing.JFrame {

      Connection con;
     
     private String userID;  // Declare userID as a field

   
   public AdminRecords1(String userID) {
        this.userID = userID;  // Set the userID after login
        initComponents();
    }
   
   public void setUserID(String userID) {
        this.userID = userID;
    }

    // Getter method to access userID
    public String getUserID() {
        return userID;
    }
     
    /**
     * Creates new form RecordPage
     */
    public AdminRecords1() {
        initComponents();
        
        String Url, User, Pass;
        Url = "jdbc:MYSQL://localhost:3306/water";
        User = "root";
        Pass = "";
        
        try{
            con = DriverManager.getConnection(Url, User, Pass);
        }catch(Exception e){
            System.out.println("Error!" + e.getLocalizedMessage());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbRecords = new javax.swing.JTable();
        viewRecord = new javax.swing.JButton();
        useradmin = new javax.swing.JButton();
        recordbtn = new javax.swing.JButton();
        requestbtn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        addRecord = new javax.swing.JButton();
        announcebtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logosmall.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/waterdrop3.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 460, -1, -1));

        tbRecords.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "FullName"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbRecords);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 780, 350));

        viewRecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/view.png"))); // NOI18N
        viewRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewRecordActionPerformed(evt);
            }
        });
        jPanel1.add(viewRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 150, 40, -1));

        useradmin.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        useradmin.setText("Users");
        useradmin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        useradmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useradminActionPerformed(evt);
            }
        });
        jPanel1.add(useradmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, 100, 40));

        recordbtn.setBackground(new java.awt.Color(102, 204, 255));
        recordbtn.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        recordbtn.setText("Records");
        recordbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        recordbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recordbtnActionPerformed(evt);
            }
        });
        jPanel1.add(recordbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, 110, 40));

        requestbtn.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        requestbtn.setText("Request");
        requestbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        requestbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestbtnActionPerformed(evt);
            }
        });
        jPanel1.add(requestbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 30, 100, 40));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logout.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 20, -1, 60));

        addRecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add.png"))); // NOI18N
        addRecord.setBorder(null);
        addRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRecordActionPerformed(evt);
            }
        });
        jPanel1.add(addRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 150, -1, -1));

        announcebtn.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        announcebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/announcement.png"))); // NOI18N
        announcebtn.setBorder(null);
        announcebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                announcebtnActionPerformed(evt);
            }
        });
        jPanel1.add(announcebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 30, 50, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void useradminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useradminActionPerformed


        AdminPage AdminPageFrame = new AdminPage();
        AdminPageFrame.setVisible(true);
        AdminPageFrame.pack();
        AdminPageFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_useradminActionPerformed

    private void recordbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recordbtnActionPerformed
        
        // TODO add your handling code here:
        
        String sql = "SELECT * FROM user";
        try{
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            DefaultTableModel model = (DefaultTableModel)tbRecords.getModel();
            model.setRowCount(0);
            while(rs.next()){
                model.addRow(new String[]{rs.getString(1),rs.getString(4)} );
                
            }
        }catch(Exception e){
            System.out.println("Error!" + e.getLocalizedMessage());
        }
    }//GEN-LAST:event_recordbtnActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        LogIn LoginFrame = new LogIn();
        LoginFrame.setVisible(true);
        LoginFrame.pack();
        LoginFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void viewRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewRecordActionPerformed

        // TODO add your handling code here:
        
        int selectedRow = tbRecords.getSelectedRow();
    
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(new JFrame(), "Please select a user from the table.", 
                                      "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    // Get the selected user's data (ID, Fullname, Email, Username, Password, etc.)
    String userID = tbRecords.getValueAt(selectedRow, 0).toString(); // Assuming ID is in column 0
    String fullName = tbRecords.getValueAt(selectedRow, 1).toString(); // Full name in column 1
    
    // Debugging: Print the selected row and userID to verify
    System.out.println("Selected Row: " + selectedRow);
    System.out.println("User ID: " + userID);
    
        AdminRecords2 AdminRecords2Frame = new AdminRecords2(userID, fullName);
        AdminRecords2Frame.setVisible(true);
        AdminRecords2Frame.pack();
        AdminRecords2Frame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_viewRecordActionPerformed

    private void addRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRecordActionPerformed
        // TODO add your handling code here:

        // Check if a row is selected in the table
     int selectedRow = tbRecords.getSelectedRow();
    
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(new JFrame(), "Please select a user from the table.", 
                                      "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    // Get the selected user's data (ID, Fullname, Email, Username, Password, etc.)
    String userID = tbRecords.getValueAt(selectedRow, 0).toString(); // Assuming ID is in column 0
    String fullName = tbRecords.getValueAt(selectedRow, 1).toString(); // Full name in column 1
    
    // Debugging: Print the selected row and userID to verify
    System.out.println("Selected Row: " + selectedRow);
    System.out.println("User ID: " + userID);
    
    // Pass the data to the crudUser form for adding
    crudRecords crudRecordsFrame = new crudRecords(userID, fullName);
    crudRecordsFrame.setVisible(true);
    crudRecordsFrame.pack();
    crudRecordsFrame.setLocationRelativeTo(null);
    this.dispose();
    }//GEN-LAST:event_addRecordActionPerformed

    private void announcebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_announcebtnActionPerformed
        Announcements AnnouncementsFrame = new Announcements();
     AnnouncementsFrame.setVisible(true);
     AnnouncementsFrame.pack();
     AnnouncementsFrame.setLocationRelativeTo(null);
     this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_announcebtnActionPerformed

    private void requestbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestbtnActionPerformed
        // TODO add your handling code here:
        RequestAdmin RequestAdminFrame = new RequestAdmin(); // Pass userID
        RequestAdminFrame.setVisible(true);
        RequestAdminFrame.pack();
        RequestAdminFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_requestbtnActionPerformed
        
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminRecords1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminRecords1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminRecords1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminRecords1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminRecords1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addRecord;
    private javax.swing.JButton announcebtn;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton recordbtn;
    private javax.swing.JButton requestbtn;
    private javax.swing.JTable tbRecords;
    private javax.swing.JButton useradmin;
    private javax.swing.JButton viewRecord;
    // End of variables declaration//GEN-END:variables
}
