import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author jerli
 */
public class AdminRecords2 extends javax.swing.JFrame {

    Connection con;
    private crudRecords CrudRecords;
    
    private String userID;
    private String fullname;
    

    // Constructor to initialize user details
    public AdminRecords2(String userID, String fullname) {
        initComponents(); // Initialize form components
        this.userID = userID;
        this.fullname = fullname;
    }
    
     public AdminRecords2(crudRecords CrudRecords) {
        this.CrudRecords = CrudRecords;
        initComponents();
    }

    public javax.swing.JTextField getSearchData() {
        return searchRecord;
    }
    
//    private javax.swing.JTextField date;
//    private javax.swing.JTextField cubic;
//    private javax.swing.JTextField balance;
//    private javax.swing.JTextField status;

    
    
    /**
     * Creates new form RecordPage2
     */
    public AdminRecords2() {
        initComponents();
        
        String Url, User, Pass;
        Url = "jdbc:MYSQL://localhost:3306/water";
        User = "root";
        Pass = "";
        
        try{
            con = DriverManager.getConnection(Url, User, Pass);
        }catch(Exception e){
            System.out.println("Error!" + e.getLocalizedMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        backbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbRecord2 = new javax.swing.JTable();
        deleteRecord = new javax.swing.JButton();
        viewRecord = new javax.swing.JButton();
        searchRecord = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        updateRecord = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/waterdrop3.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 460, -1, -1));

        backbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/back.png"))); // NOI18N
        backbtn.setBorder(null);
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });
        jPanel1.add(backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        tbRecord2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "DATE", "CUBIC", "AMOUNT", "BALANCE", "TOTAL AMOUNT", "REMARKS"
            }
        ));
        jScrollPane1.setViewportView(tbRecord2);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 860, 430));

        deleteRecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete.png"))); // NOI18N
        deleteRecord.setBorder(null);
        deleteRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteRecordActionPerformed(evt);
            }
        });
        jPanel1.add(deleteRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 140, -1, -1));

        viewRecord.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        viewRecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/view.png"))); // NOI18N
        viewRecord.setBorder(null);
        viewRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewRecordActionPerformed(evt);
            }
        });
        jPanel1.add(viewRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 140, -1, 40));

        searchRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchRecordActionPerformed(evt);
            }
        });
        jPanel1.add(searchRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 440, 40));

        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search.png"))); // NOI18N
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jPanel1.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 90, -1, -1));

        updateRecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/update.png"))); // NOI18N
        updateRecord.setText("\n");
        updateRecord.setBorder(null);
        updateRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateRecordActionPerformed(evt);
            }
        });
        jPanel1.add(updateRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 140, 40, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
        
        AdminRecords1 RecordFrame = new AdminRecords1();
        RecordFrame.setVisible(true);
        RecordFrame.pack();
        RecordFrame.setLocationRelativeTo(null); 
        this.dispose();
    }//GEN-LAST:event_backbtnActionPerformed

    private void viewRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewRecordActionPerformed

        // TODO add your handling code here:

       
    // Define the database connection variables
    String Url = "jdbc:mysql://localhost:3306/water";
    String User = "root";
    String Pass = "";

    // Initialize the connection object
    Connection con = null;

    try {
        // Load the database driver and establish the connection
        Class.forName("com.mysql.cj.jdbc.Driver");
        con = DriverManager.getConnection(Url, User, Pass);

        // Prepare SQL query to select records based on userID
        String sql = "SELECT * FROM record WHERE userID = ?";
        PreparedStatement pst = con.prepareStatement(sql);
        pst.setString(1, userID);  // Bind userID to the query

        // Execute the query
        ResultSet rs = pst.executeQuery();

        // Create or clear the table model before adding new data
        DefaultTableModel model = (DefaultTableModel) tbRecord2.getModel();
        model.setRowCount(0); // Clear any existing rows

        // Add the fetched data to the table model
        while (rs.next()) {
            // Add each row of data to the table. Adjust the columns as needed.
            model.addRow(new Object[]{
                rs.getString("recordID"),  // Assuming the first column is recordID
                rs.getString("date"),      // Date column
                rs.getString("cubic"),     // Cubic column
                rs.getString("amount"),    // Amount column
                rs.getString("balance"),   // Balance column
                rs.getString("total_amount"), // Total Amount column
                rs.getString("remarks")
            });
        }
    } catch (Exception e) {
        // Handle errors
        System.out.println("Error: " + e.getLocalizedMessage());
    } finally {
        // Close the connection in the 'finally' block to ensure it gets closed even if an error occurs
        try {
            if (con != null && !con.isClosed()) {
                con.close();
            }
        } catch (Exception ex) {
            System.out.println("Error closing connection: " + ex.getLocalizedMessage());
        }
    }
    }//GEN-LAST:event_viewRecordActionPerformed

    private void deleteRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteRecordActionPerformed
        // TODO add your handling code here:
        
        try {
        // Check if a row is selected in the table
        int selectedRow = tbRecord2.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(new JFrame(), "Please select a Record from the table.", 
                                          "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Get the ID from the selected row
        String ID = tbRecord2.getValueAt(selectedRow, 0).toString(); // Assuming ID is in column 0
        
        Class.forName("com.mysql.cj.jdbc.Driver");
        String Url = "jdbc:mysql://localhost:3306/water";
        String User = "root";
        String Pass = "";
        
        Connection con = DriverManager.getConnection(Url, User, Pass);
        String sql = "DELETE FROM record WHERE recordID = ?";
        
        // Use PreparedStatement to execute the query
        PreparedStatement pst = con.prepareStatement(sql);
        pst.setString(1, ID);
        int rowsAffected = pst.executeUpdate();
        
        if (rowsAffected > 0) {
            // Remove the row from the table model
            ((DefaultTableModel) tbRecord2.getModel()).removeRow(selectedRow);
            JOptionPane.showMessageDialog(new JFrame(), "Record deleted successfully.", 
                                          "Success", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(new JFrame(), "Invalid ID.", 
                                          "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        con.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(new JFrame(), "Error: " + e.getMessage(), 
                                      "Error", JOptionPane.ERROR_MESSAGE);
    }
        
    }//GEN-LAST:event_deleteRecordActionPerformed

    private void searchRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchRecordActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_searchRecordActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:

                                    
    // TODO add your handling code here:

    String Url = "jdbc:mysql://localhost:3306/water";  
    String User = "root";
    String Pass = "";

    // Get the date to search for
    String searchDate = searchRecord.getText();

    try {
        // Load the MySQL JDBC Driver
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con = DriverManager.getConnection(Url, User, Pass);

        // Check if the searchDate is empty
        if ("".equals(searchDate)) {
            JOptionPane.showMessageDialog(new JFrame(), "Please enter a date to search", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Query to fetch the record based on date
        String query = "SELECT * FROM record WHERE date = ?";
        PreparedStatement pstmt = con.prepareStatement(query);
        pstmt.setString(1, searchDate); // Set the searchDate parameter

        ResultSet rs = pstmt.executeQuery();

        if (rs.next()) {
            // Create or access an instance of crudRecords
            crudRecords crud = new crudRecords();

            // Update the fields in crudRecords with values from the record table
            crud.getDate().setText(rs.getString("date")); // Example field
            crud.getCubic().setText(rs.getString("cubic")); // Example field
            crud.getBalance().setText(rs.getString("balance")); // Example field
            // crud.getAmount().setText(rs.getString("amount"));
            crud.getRemarks().setText(rs.getString("remarks"));

            // Optionally, display the crudRecords window if it isn't already visible
            crud.setVisible(true);

            con.close();
        } else {
            JOptionPane.showMessageDialog(new JFrame(), "No matching record found", "Error",
                JOptionPane.ERROR_MESSAGE);
        }
    } catch (Exception e) {
        System.out.println("Error: " + e.getMessage());
    }
    
        
    }//GEN-LAST:event_searchActionPerformed

    private void updateRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateRecordActionPerformed
        // TODO add your handling code here:
        
                                           
    // Check if a row is selected in the table
    int selectedRow = tbRecord2.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(new JFrame(), "Please select a user from the table.", 
                                      "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
   
    String userID = tbRecord2.getValueAt(selectedRow, 0).toString();
    String date = tbRecord2.getValueAt(selectedRow, 1).toString(); 
    String cubic = tbRecord2.getValueAt(selectedRow, 2).toString(); 
//    String amount = tbRecord2.getValueAt(selectedRow, 3).toString(); 
    String balance = tbRecord2.getValueAt(selectedRow, 4).toString(); 
//    String totalAmount = tbRecord2.getValueAt(selectedRow, 5).toString(); 
    String remarks = tbRecord2.getValueAt(selectedRow, 6).toString(); 
    
    // Ensure data is not null or empty
    if (userID.isEmpty() || date.isEmpty() || cubic.isEmpty() || balance.isEmpty() || remarks.isEmpty()) {
        JOptionPane.showMessageDialog(new JFrame(), "Some data fields are empty.", 
                                      "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    // Pass the data to the crudUser form for updating
    crudRecords crudRecordsFrame = new crudRecords(userID, date, cubic, balance, remarks );
    crudRecordsFrame.setVisible(true);
    crudRecordsFrame.pack();
    crudRecordsFrame.setLocationRelativeTo(null); 
    this.dispose();  // Close the current AdminPage window

    }//GEN-LAST:event_updateRecordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminRecords2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminRecords2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminRecords2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminRecords2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminRecords2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbtn;
    private javax.swing.JButton deleteRecord;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton search;
    private javax.swing.JTextField searchRecord;
    private javax.swing.JTable tbRecord2;
    private javax.swing.JButton updateRecord;
    private javax.swing.JButton viewRecord;
    // End of variables declaration//GEN-END:variables
}
