import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author jerli
 */
public class Announcements extends javax.swing.JFrame {
    Connection con;

    private String userID;
    public void setUserID(String userID) {
        this.userID = userID;
    }

    // Getter method to access userID
    public String getUserID() {
        return userID;
    }

    /**
     * Creates new form Connection
     */
    public Announcements() {
        initComponents();
        
        String Url, User, Pass;
        Url = "jdbc:MYSQL://localhost:3306/water";
        User = "root";
        Pass = "";
        
        try{
            con = DriverManager.getConnection(Url, User, Pass);
        }catch(Exception e){
            System.out.println("Error!" + e.getLocalizedMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        useradmin = new javax.swing.JButton();
        recordbtn = new javax.swing.JButton();
        announcebtn = new javax.swing.JButton();
        requestbtn = new javax.swing.JButton();
        logoutbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        anncontent = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        anndate = new javax.swing.JTextField();
        anntitle = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logosmall.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        useradmin.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        useradmin.setText("Users");
        useradmin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        useradmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useradminActionPerformed(evt);
            }
        });
        jPanel1.add(useradmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 100, 40));

        recordbtn.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        recordbtn.setText("Records");
        recordbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        recordbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recordbtnActionPerformed(evt);
            }
        });
        jPanel1.add(recordbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, 110, 40));

        announcebtn.setBackground(new java.awt.Color(0, 204, 255));
        announcebtn.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        announcebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/announcement.png"))); // NOI18N
        announcebtn.setBorder(null);
        announcebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                announcebtnActionPerformed(evt);
            }
        });
        jPanel1.add(announcebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 30, 50, 40));

        requestbtn.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        requestbtn.setText("Request");
        requestbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        requestbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestbtnActionPerformed(evt);
            }
        });
        jPanel1.add(requestbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 30, 100, 40));

        logoutbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logout.png"))); // NOI18N
        logoutbtn.setBorder(null);
        logoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbtnActionPerformed(evt);
            }
        });
        jPanel1.add(logoutbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 10, 60, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/waterdrop3.png"))); // NOI18N
        jLabel2.setToolTipText("");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 400, -1, -1));

        anncontent.setColumns(20);
        anncontent.setRows(5);
        anncontent.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jScrollPane1.setViewportView(anncontent);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, 490, 170));

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel3.setText("   CONTENT");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 140, 50));

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel4.setText("     TITLE");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 140, 50));

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel5.setText("      DATE");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 140, 50));

        anndate.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        anndate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(anndate, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 490, 40));

        anntitle.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        anntitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(anntitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 490, 40));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 150, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 40, 930, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void useradminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useradminActionPerformed

        // TODO add your handling code here:
        
        AdminPage AdminPageFrame = new AdminPage();
        AdminPageFrame.setVisible(true);
        AdminPageFrame.pack();
        AdminPageFrame.setLocationRelativeTo(null);
        this.dispose();
        
    }//GEN-LAST:event_useradminActionPerformed

    private void recordbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recordbtnActionPerformed
        AdminRecords1 AdminRecords1Frame = new AdminRecords1();
        AdminRecords1Frame.setVisible(true);
        AdminRecords1Frame.pack();
        AdminRecords1Frame.setLocationRelativeTo(null);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_recordbtnActionPerformed

    private void announcebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_announcebtnActionPerformed

        
     Announcements AnnouncementsFrame = new Announcements();
     AnnouncementsFrame.setVisible(true);
     AnnouncementsFrame.pack();
     AnnouncementsFrame.setLocationRelativeTo(null);
     this.dispose();



        // TODO add your handling code here:
    }//GEN-LAST:event_announcebtnActionPerformed

    private void logoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbtnActionPerformed

        LogIn LoginFrame = new LogIn();
        LoginFrame.setVisible(true);
        LoginFrame.pack();
        LoginFrame.setLocationRelativeTo(null);
        this.dispose();
        }

        public void setUser(String name){
            //        user.setText("Hi, " + name + "!");

            // TODO add your handling code here:
    }//GEN-LAST:event_logoutbtnActionPerformed

    private void requestbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestbtnActionPerformed
        // TODO add your handling code here:
        
        RequestAdmin RequestAdminFrame = new RequestAdmin(); // Pass userID
        RequestAdminFrame.setVisible(true);
        RequestAdminFrame.pack();
        RequestAdminFrame.setLocationRelativeTo(null);
        this.dispose();
        
    }//GEN-LAST:event_requestbtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
  
   
    String Url = "jdbc:mysql://localhost:3306/water";  
    String User = "root";
    String Pass = "";

    // Input field variables
    String Date, Title, Content;

    try {
        // Load the MySQL JDBC Driver
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con = DriverManager.getConnection(Url, User, Pass);

        // Validation for empty fields
        if ("".equals(anndate.getText())) {
            JOptionPane.showMessageDialog(new JFrame(), "Date is required", "Error", JOptionPane.ERROR_MESSAGE);
        } else if ("".equals(anntitle.getText())) {
            JOptionPane.showMessageDialog(new JFrame(), "Title is required", "Error", JOptionPane.ERROR_MESSAGE);
        } else if ("".equals(anncontent.getText())) {
            JOptionPane.showMessageDialog(new JFrame(), "Content is required", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            // Retrieve input values
            Date = anndate.getText();
            Title = anntitle.getText();
            Content = anncontent.getText();

            // Insert data into the database
            String query = "INSERT INTO announcement(announcement_date, title, content) VALUES(?, ?, ?)";

            PreparedStatement pstmt = con.prepareStatement(query);
             pstmt.setDate(1, java.sql.Date.valueOf(Date)); // Convert string to java.sql.Date
            pstmt.setString(2, Title);
            pstmt.setString(3, Content);
           

            pstmt.executeUpdate();

            // Reset the fields
            anndate.setText("");
            anntitle.setText("");
            anncontent.setText("");

            JOptionPane.showMessageDialog(null, "Announcement Successfully Recorded!");
        }
    } catch (IllegalArgumentException iae) {
        JOptionPane.showMessageDialog(new JFrame(), "Invalid date format. Use YYYY-MM-DD", "Input Error", JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        System.out.println("Error! " + e.getLocalizedMessage());
        JOptionPane.showMessageDialog(new JFrame(), "Error: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
    }



    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Announcements.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Announcements.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Announcements.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Announcements.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Announcements().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea anncontent;
    private javax.swing.JTextField anndate;
    private javax.swing.JButton announcebtn;
    private javax.swing.JTextField anntitle;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logoutbtn;
    private javax.swing.JButton recordbtn;
    private javax.swing.JButton requestbtn;
    private javax.swing.JButton useradmin;
    // End of variables declaration//GEN-END:variables
}
