/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import static javax.swing.JOptionPane.showMessageDialog;



/**
 *
 * @author jerli
 */
public class crudRecords extends javax.swing.JFrame {
    
    private String userID;
    private String fullname;
    private String recordID;

    // Constructor to initialize user details
    public crudRecords(String userID, String fullname) {
        initComponents(); // Initialize form components
        this.userID = userID;
        this.fullname = fullname;

    }
    
     public javax.swing.JTextField getDate() {
        return date;
    }

    public javax.swing.JTextField getCubic() {
        return cubic;
    }

    public javax.swing.JTextField getBalance() {
        return balance;
    }
    

    
    public javax.swing.JTextField getRemarks() {
        return remarks;
    }
    
//    public crudRecords(String recordID, String date, String cubic, String balance, String status) {
//        initComponents();
//    }
    
    private AdminRecords2 adminRecords2;

    public crudRecords(AdminRecords2 adminRecords2) {
        this.adminRecords2 = adminRecords2;
        initComponents();
    }
    
    public crudRecords(String userID, String date, String cubic, String balance,  String remarks) {
    initComponents();
    this.userID = userID;
    
        getDate().setText(date);
        getCubic().setText(cubic);
        getBalance().setText(balance);
        getRemarks().setText(remarks);
    }

    /**
     * Creates new form crudRecords
     */
    public crudRecords() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        date = new javax.swing.JTextField();
        cubic = new javax.swing.JTextField();
        balance = new javax.swing.JTextField();
        remarks = new javax.swing.JTextField();
        submitbtn = new javax.swing.JButton();
        backbtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        updateRecords = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel1.setText("    DATE");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 160, 50));

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel2.setText("    CUBIC");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 160, 50));

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel3.setText("    BALANCE");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 160, 50));

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel5.setText("REMARKS");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 160, 50));

        date.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(153, 153, 153)));
        date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateActionPerformed(evt);
            }
        });
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 470, 40));

        cubic.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(153, 153, 153)));
        jPanel1.add(cubic, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 470, 40));

        balance.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(153, 153, 153)));
        jPanel1.add(balance, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, 470, 40));

        remarks.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(153, 153, 153)));
        jPanel1.add(remarks, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, 470, 40));

        submitbtn.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        submitbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add.png"))); // NOI18N
        submitbtn.setBorder(null);
        submitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbtnActionPerformed(evt);
            }
        });
        jPanel1.add(submitbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 40, 40, 40));

        backbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/back.png"))); // NOI18N
        backbtn.setBorder(null);
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });
        jPanel1.add(backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/waterdrop3.png"))); // NOI18N
        jLabel4.setToolTipText("");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 390, -1, -1));

        updateRecords.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/update.png"))); // NOI18N
        updateRecords.setBorder(null);
        updateRecords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateRecordsActionPerformed(evt);
            }
        });
        jPanel1.add(updateRecords, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 40, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateActionPerformed

    private void submitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbtnActionPerformed
        // TODO add your handling code here:
        
     String Url = "jdbc:mysql://localhost:3306/water";  
    String User = "root";
    String Pass = "";

    // Input field variables
    String Date, Cubic, Balance, Amount, Remarks, UserID, TotalAmount;

    try {
        // Load the MySQL JDBC Driver
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con = DriverManager.getConnection(Url, User, Pass);

        // Validation for empty fields
        if ("".equals(date.getText())) {
            JOptionPane.showMessageDialog(new JFrame(), "Date is required", "Error", JOptionPane.ERROR_MESSAGE);
        } else if ("".equals(cubic.getText())) {
            JOptionPane.showMessageDialog(new JFrame(), "Cubic is required", "Error", JOptionPane.ERROR_MESSAGE);
        } else if ("".equals(balance.getText())) {
            JOptionPane.showMessageDialog(new JFrame(), "Balance is required", "Error", JOptionPane.ERROR_MESSAGE);
        } else if ("".equals(remarks.getText())) {  // Changed from 'status' to 'remarks'
            JOptionPane.showMessageDialog(new JFrame(), "Remarks is required", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            // Retrieve input values
            Date = date.getText();
            Cubic = cubic.getText();
            Balance = balance.getText();
            Remarks = remarks.getText();

            // Calculate the Amount
            double cubicValue = Double.parseDouble(Cubic);
            double balanceValue = Double.parseDouble(Balance);
            double amountValue = cubicValue * 300.00; // Calculate the amount based on cubic input
            double totalAmountValue = amountValue + balanceValue; // Calculate totalAmount

            // Set the amount and totalAmount
            Amount = String.valueOf(amountValue);
            TotalAmount = String.valueOf(totalAmountValue);

            // **UserID Retrieval**
            // Replace this with how you retrieve the userID in your application
            UserID = userID;  // Example: Set userID to 1 for now (Ensure it exists in the related table)

            // Insert data into the database
            String query = "INSERT INTO record(date, cubic, amount, balance, total_amount, remarks, userID) " +
                           "VALUES(?, ?, ?, ?, ?, ?, ?)";

            PreparedStatement pstmt = con.prepareStatement(query);
            pstmt.setString(1, Date);
            pstmt.setInt(2, Integer.parseInt(Cubic));  // Assuming cubic is an integer
            pstmt.setDouble(3, amountValue);  // Balance is a decimal (Double)
            pstmt.setDouble(4, Double.parseDouble(Balance));  // Store the calculated amount
            pstmt.setDouble(5, totalAmountValue);  // Store the calculated totalAmount
            pstmt.setString(6, Remarks);
            pstmt.setString(7, UserID);

            pstmt.executeUpdate();

            // Reset the fields except for the calculated amount (optional)
            date.setText("");
            cubic.setText("");
            balance.setText("");
            remarks.setText("");  // Reset remarks field

            JOptionPane.showMessageDialog(null, "Successfully Recorded!");
        }
    } catch (NumberFormatException nfe) {
        JOptionPane.showMessageDialog(new JFrame(), "Invalid numeric input for Cubic or Balance", "Input Error", JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        System.out.println("Error! " + e.getLocalizedMessage());
        JOptionPane.showMessageDialog(new JFrame(), "Error: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
    }

        
    }//GEN-LAST:event_submitbtnActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
        AdminRecords1 AdminRecords1Frame = new AdminRecords1 ();
        AdminRecords1Frame.setVisible(true);
        AdminRecords1Frame.pack();
        AdminRecords1Frame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_backbtnActionPerformed

    private void updateRecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateRecordsActionPerformed
        // TODO add your handling code here:
        
//     String userID = userIDField.getText();
//    String date = getDate().getText();
//    String cubic = getCubic().getText();
//    String balance = getBalance().getText();
//    String remarks = getRemarks().getText();
    
    
                                       
    // Input fields
    String Date = date.getText();
    String Cubic = cubic.getText();
    String Balance = balance.getText();
    String Remarks = remarks.getText();
    
    // Validate input
    if (Date.isEmpty() || Cubic.isEmpty() || Balance.isEmpty() || Remarks.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please fill in all fields", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    try {
        // Parse numeric inputs
        double cubicValue = Double.parseDouble(Cubic);
        double balanceValue = Double.parseDouble(Balance);
        double amountValue = cubicValue * 300.00; // Calculate the amount based on cubic input
        double totalAmountValue = amountValue + balanceValue; // Calculate totalAmount

        // Set the calculated values
        String Amount = String.valueOf(amountValue);
        String TotalAmount = String.valueOf(totalAmountValue);

        // Perform the database update
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/water", "root", "");
        String sql = "UPDATE record SET date = ?, cubic = ?, amount = ?, balance = ?, total_amount = ?, remarks = ? WHERE recordID = ?";
        
        PreparedStatement pst = con.prepareStatement(sql);
        pst.setString(1, Date);
        pst.setInt(2, Integer.parseInt(Cubic)); // Assuming cubic is an integer
        pst.setDouble(3, amountValue);
        pst.setDouble(4, balanceValue);
        pst.setDouble(5, totalAmountValue);
        pst.setString(6, Remarks);
        pst.setString(7, userID); // Use the userID passed from the context
        
        int rowsAffected = pst.executeUpdate();
        
        if (rowsAffected > 0) {
            JOptionPane.showMessageDialog(this, "Record updated successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
            // Reset fields after successful update
            date.setText("");
            cubic.setText("");
            balance.setText("");
            remarks.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "Failed to update record", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } catch (NumberFormatException nfe) {
        JOptionPane.showMessageDialog(this, "Invalid numeric input for Cubic or Balance", "Input Error", JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
    }


    }//GEN-LAST:event_updateRecordsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(crudRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(crudRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(crudRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(crudRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new crudRecords().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbtn;
    private javax.swing.JTextField balance;
    private javax.swing.JTextField cubic;
    private javax.swing.JTextField date;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField remarks;
    private javax.swing.JButton submitbtn;
    private javax.swing.JButton updateRecords;
    // End of variables declaration//GEN-END:variables
}
