import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author jerli
 */
public class crudUser extends javax.swing.JFrame {



    // Provide getter methods for each field
    public javax.swing.JTextField getFname() {
        return fname;
    }

    public javax.swing.JTextField getEmailAddress() {
        return emailAddress;
    }

    public javax.swing.JTextField getUname() {
        return uname;
    }

    public javax.swing.JTextField getPass() {
        return pass;
    }

    public javax.swing.JTextField getConPass() {
        return conpass;
    }
    
    private AdminPage adminPage;

    public crudUser(AdminPage adminPage) {
        this.adminPage = adminPage;
        initComponents();
    }
    
    private String userID; // Store the userID for updating in the database
    
   
    
    
    
    /**
     * Creates new form crudUser
     */
    public crudUser(String userID, String fullName, String email) {
        initComponents();
        this.userID = userID;
        
        getFname().setText(fullName);
        getEmailAddress().setText(email);
        
    }
    
    public crudUser() {
        initComponents();
    }
    
    
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        emailAddress = new javax.swing.JTextField();
        uname = new javax.swing.JTextField();
        addbtn = new javax.swing.JButton();
        updatebtn = new javax.swing.JButton();
        backbtn = new javax.swing.JButton();
        conpass = new javax.swing.JPasswordField();
        pass = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                formInputMethodTextChanged(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Fullname: ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, -1));

        jLabel2.setText("Email: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, -1, -1));

        jLabel3.setText("Username: ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, -1, -1));

        jLabel4.setText("Password: ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 180, -1, -1));

        jLabel5.setText("Confirm Password: ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 290, -1, -1));
        jPanel1.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 280, 40));

        emailAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailAddressActionPerformed(evt);
            }
        });
        jPanel1.add(emailAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 270, 40));
        jPanel1.add(uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, 270, 40));

        addbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add.png"))); // NOI18N
        addbtn.setBorder(null);
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });
        jPanel1.add(addbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 90, -1, -1));

        updatebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/update.png"))); // NOI18N
        updatebtn.setBorder(null);
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });
        jPanel1.add(updatebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 90, -1, -1));

        backbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/back.png"))); // NOI18N
        backbtn.setBorder(null);
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });
        jPanel1.add(backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));
        jPanel1.add(conpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 320, 300, 40));
        jPanel1.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, 300, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/waterdrop3.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 450, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_formInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_formInputMethodTextChanged

    private void emailAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailAddressActionPerformed

    
    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
        // TODO add your handling code here:

        String fn, em, un, pw, cpw, query;
        
        
        //connect to database
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            
            String Url = "jdbc:MySQL://localhost:3306/water";
            String User = "root";
            String Pass = "";
            
            Connection con = DriverManager.getConnection(Url, User, Pass);
            Statement st = con.createStatement();
            
            if("".equals(fname.getText())){
             
                JOptionPane.showMessageDialog(new JFrame(), "First Name is required", "Dialog",
                                     JOptionPane.ERROR_MESSAGE);
            }else if("".equals(emailAddress.getText())){
             
                JOptionPane.showMessageDialog(new JFrame(), "Email Address is required", "Dialog",
                                     JOptionPane.ERROR_MESSAGE);
                
            }else if("".equals(uname.getText())){
             
                JOptionPane.showMessageDialog(new JFrame(), "Username is required", "Dialog",
                                     JOptionPane.ERROR_MESSAGE);
            }else if("".equals(pass.getText())){
             
                JOptionPane.showMessageDialog(new JFrame(), "Password is required", "Dialog",
                                     JOptionPane.ERROR_MESSAGE);
                
            }else if("".equals(conpass.getText())){
             
                JOptionPane.showMessageDialog(new JFrame(), "Confirm Password is required", "Dialog",
                                     JOptionPane.ERROR_MESSAGE);
            }else {
                fn = fname.getText();
                em = emailAddress.getText();
                un = uname.getText();
                pw = pass.getText();
                cpw = conpass.getText();
                query = "INSERT INTO user (fullname, email, username, password, confirm_password) "
                        + "VALUES ('"+fn+"','"+em+"','"+un+"','"+pw+"','"+cpw+"')";
               
               st.executeUpdate(query);
               fname.setText("");
               emailAddress.setText("");
               uname.setText("");
               pass.setText("");
               conpass.setText("");
               showMessageDialog(null, "Successfully Added.");
//               loadData(); para sa pag view ata to
               con.close();
            }   
        }catch(Exception e){
            System.out.println("Error "+ e.getMessage());
            
        }
        
    }//GEN-LAST:event_addbtnActionPerformed

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
        // TODO add your handling code here:
        
        String fullName = getFname().getText();
        String email = getEmailAddress().getText();
        String username = getUname().getText();
        String password = getPass().getText();
        String confirm_password = getConPass().getText();
        
        // Validate input
        if (fullName.isEmpty() || email.isEmpty() || username.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in all fields", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Check if password and confirm password match
        if (!password.equals(confirm_password)) {
            JOptionPane.showMessageDialog(this, "Passwords do not match", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Perform the database update
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/water", "root", "");
            String sql = "UPDATE user SET fullname = ?, email = ?, username = ?, password = ?, confirm_password = ? WHERE userID = ?";
            
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, fullName);
            pst.setString(2, email);
            pst.setString(3, username);
            pst.setString(4, password);
            pst.setString(5, confirm_password);
            pst.setString(6, userID);  // Use the userID passed from AdminPage to identify the user
            
            int rowsAffected = pst.executeUpdate();
            
            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(this, "User updated successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
//                this.dispose();  // Close the crudUser form after update
            } else {
                JOptionPane.showMessageDialog(this, "Failed to update user", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    


    }//GEN-LAST:event_updatebtnActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:

        AdminPage AdminPageFrame = new AdminPage();
        AdminPageFrame.setVisible(true);
        AdminPageFrame.pack();
        AdminPageFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_backbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(crudUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(crudUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(crudUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(crudUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               new crudUser().setVisible(true);

//                crudUser x = new crudUser();
//                x.loadData();
//                x.setLocationRelativeTo(null);
//                x.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbtn;
    private javax.swing.JButton backbtn;
    private javax.swing.JPasswordField conpass;
    private javax.swing.JTextField emailAddress;
    private javax.swing.JTextField fname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField pass;
    private javax.swing.JTextField uname;
    private javax.swing.JButton updatebtn;
    // End of variables declaration//GEN-END:variables
}
