/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jerli
 */
public class ListofRequest extends javax.swing.JFrame {
    
    Connection con;
    
    private String userID;
    private String fullname;
    
    private RequestUser requestuser;
    public ListofRequest(RequestUser requestuser) {
        this.requestuser = requestuser;
        initComponents();
    }
    
    
    private RequestField requestField;

    public ListofRequest(RequestField requestField) {
        this.requestField = requestField;
        initComponents();
    }
    

    // Constructor to initialize user details
    public ListofRequest(String userID, String fullname) {
        initComponents(); // Initialize form components
        this.userID = userID;
        this.fullname = fullname;
    }

    /**
     * Creates new form ListofRequest
     */
    public ListofRequest() {
        initComponents();
        
         String Url, User, Pass;
        Url = "jdbc:MYSQL://localhost:3306/water";
        User = "root";
        Pass = "";
        
        try{
            con = DriverManager.getConnection(Url, User, Pass);
        }catch(Exception e){
            System.out.println("Error!" + e.getLocalizedMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        view = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbviewRequest = new javax.swing.JTable();
        update = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        view.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/view.png"))); // NOI18N
        view.setBorder(null);
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });
        jPanel1.add(view, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 50, -1, -1));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/back.png"))); // NOI18N
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        tbviewRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "REQUEST DATE", "REQUEST TYPE", "NOTES", "STATUS"
            }
        ));
        jScrollPane1.setViewportView(tbviewRequest);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 740, 170));

        update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/update.png"))); // NOI18N
        update.setBorder(null);
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel1.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 50, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 50, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
        // TODO add your handling code here:
 
                                    
   

    String Url = "jdbc:mysql://localhost:3306/water";
    String User = "root";
    String Pass = "";

    // Initialize the connection object
    Connection con = null;

    try {
        // Load the database driver and establish the connection
        Class.forName("com.mysql.cj.jdbc.Driver");
        con = DriverManager.getConnection(Url, User, Pass);

        // Prepare SQL query to select records based on userID
        String sql = "SELECT * FROM request WHERE userID = ?";
        PreparedStatement pst = con.prepareStatement(sql);
        pst.setString(1, userID);  // Bind userID to the query

        // Execute the query
        ResultSet rs = pst.executeQuery();

        // Create or clear the table model before adding new data
        DefaultTableModel model = (DefaultTableModel) tbviewRequest.getModel();
        model.setRowCount(0); // Clear any existing rows

        // Add the fetched data to the table model
        while (rs.next()) {
            // Add each row of data to the table. Adjust the columns as needed.
            model.addRow(new Object[]{
                rs.getString("requestID"),
                rs.getString("request_date"),
                rs.getString("request_type"),
                rs.getString("notes"),
                rs.getString("status"),  // Fetch the current status
                rs.getString("userID"),
                
            });
        }
    } catch (Exception e) {
        // Handle errors
        System.out.println("Error: " + e.getLocalizedMessage());
    } finally {
        // Close the connection in the 'finally' block to ensure it gets closed even if an error occurs
        try {
            if (con != null && !con.isClosed()) {
                con.close();
            }
        } catch (Exception ex) {
            System.out.println("Error closing connection: " + ex.getLocalizedMessage());
        }
    }

    }//GEN-LAST:event_viewActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        
        RequestAdmin RequestFrame = new RequestAdmin();
        RequestFrame.setVisible(true);
        RequestFrame.pack();
        RequestFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed


    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed

        int selectedRow = tbviewRequest.getSelectedRow();
if (selectedRow == -1) {
    JOptionPane.showMessageDialog(new JFrame(), "Please select a request from the table.", 
                                  "Error", JOptionPane.ERROR_MESSAGE);
    return;
}

// Get the selected request's data (ID, Request Date, Request Type, Notes, Status)
 String userID = tbviewRequest.getValueAt(selectedRow, 0).toString(); // Assuming ID is in column 0
String requestDate = tbviewRequest.getValueAt(selectedRow, 1).toString(); // Request Date in column 1
String requestType = tbviewRequest.getValueAt(selectedRow, 2).toString(); // Request Type in column 2
String notes = tbviewRequest.getValueAt(selectedRow, 3).toString(); // Notes in column 3
String status = tbviewRequest.getValueAt(selectedRow, 4).toString(); // Status in column 4

// Pass the data to the crudRequest form for updating
RequestField RequestFieldFrame = new RequestField(userID, requestDate, requestType, notes, status);
RequestFieldFrame.setVisible(true);
RequestFieldFrame.pack();
RequestFieldFrame.setLocationRelativeTo(null); 
this.dispose();  // Close the current window

    
      
    }//GEN-LAST:event_updateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
           try {
        // Check if a row is selected in the table
        int selectedRow = tbviewRequest.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(new JFrame(), "Please select a Request from the table.", 
                                          "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Get the ID from the selected row
        String ID = tbviewRequest.getValueAt(selectedRow, 0).toString(); // Assuming ID is in column 0
        
        Class.forName("com.mysql.cj.jdbc.Driver");
        String Url = "jdbc:mysql://localhost:3306/water";
        String User = "root";
        String Pass = "";
        
        Connection con = DriverManager.getConnection(Url, User, Pass);
        String sql = "DELETE FROM request WHERE requestID = ?";
        
        // Use PreparedStatement to execute the query
        PreparedStatement pst = con.prepareStatement(sql);
        pst.setString(1, ID);
        int rowsAffected = pst.executeUpdate();
        
        if (rowsAffected > 0) {
            // Remove the row from the table model
            ((DefaultTableModel) tbviewRequest.getModel()).removeRow(selectedRow);
            JOptionPane.showMessageDialog(new JFrame(), "Resquest deleted successfully.", 
                                          "Success", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(new JFrame(), "Invalid ID.", 
                                          "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        con.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(new JFrame(), "Error: " + e.getMessage(), 
                                      "Error", JOptionPane.ERROR_MESSAGE);
    }
           
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListofRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListofRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListofRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListofRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListofRequest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbviewRequest;
    private javax.swing.JButton update;
    private javax.swing.JButton view;
    // End of variables declaration//GEN-END:variables
}
