
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author jerli
 */
public class LogIn extends javax.swing.JFrame {

    /**
     * Creates new form LogIn
     */
    public LogIn() {
        initComponents();
        this.setResizable(false); //to fix the size
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        unamelogin = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        signupbtn = new javax.swing.JButton();
        passlogin = new javax.swing.JPasswordField();
        loginbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(7, 79, 132));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logo.png"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 80, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 660));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bg1.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, -1, 190));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bg2.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 470, -1, -1));

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 48)); // NOI18N
        jLabel3.setText("WELCOME");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        jLabel4.setText("Username: ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, -1, -1));

        unamelogin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        unamelogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unameloginActionPerformed(evt);
            }
        });
        jPanel1.add(unamelogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 250, 330, 40));

        jLabel5.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        jLabel5.setText("Password: ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 340, -1, -1));

        jLabel6.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14)); // NOI18N
        jLabel6.setText("Create an account?");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 490, -1, -1));

        signupbtn.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        signupbtn.setForeground(new java.awt.Color(0, 74, 173));
        signupbtn.setText("SignUp here.");
        signupbtn.setBorder(null);
        signupbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupbtnActionPerformed(evt);
            }
        });
        jPanel1.add(signupbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 490, -1, -1));

        passlogin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, new java.awt.Color(0, 0, 0), java.awt.Color.black, java.awt.Color.black));
        passlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passloginActionPerformed(evt);
            }
        });
        jPanel1.add(passlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 370, 320, 40));

        loginbtn.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        loginbtn.setText("LogIn");
        loginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbtnActionPerformed(evt);
            }
        });
        jPanel1.add(loginbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 450, 100, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 670));

        setSize(new java.awt.Dimension(1056, 669));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void signupbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupbtnActionPerformed
      
//        this.hide(); //current frame hide when i click the signup
//        SignUp signupObj = new SignUp();
//        signupObj.show(); //diplay the signup 

        SignUp SignUpFrame = new SignUp();
        SignUpFrame.setVisible(true);
        SignUpFrame.pack();
        SignUpFrame.setLocationRelativeTo(null); 
        this.dispose();
        
// TODO add your handling code here:
    }//GEN-LAST:event_signupbtnActionPerformed

    private void unameloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unameloginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unameloginActionPerformed

    private void loginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbtnActionPerformed

        String Username, Password, query, fname = null, emailAddress = null, conpass = null, passDb = null, userID = null;
String Url, User, Pass;
Url = "jdbc:MYSQL://localhost:3306/water";
User = "root";
Pass = "";
int notFound = 0;

// Define admin credentials (hardcoded)
String adminUsername = "admin"; // Replace with your admin username
String adminPassword = "admin"; // Replace with your admin password

try {
    Class.forName("com.mysql.cj.jdbc.Driver");
    Connection con = DriverManager.getConnection(Url, User, Pass);
    Statement st = con.createStatement();

    if ("".equals(unamelogin.getText())) {
        JOptionPane.showMessageDialog(new JFrame(), "Username is required!", "Error", JOptionPane.ERROR_MESSAGE);
    } else if ("".equals(passlogin.getText())) {
        JOptionPane.showMessageDialog(new JFrame(), "Password is required!", "Error", JOptionPane.ERROR_MESSAGE);
    } else {
        Username = unamelogin.getText();
        Password = passlogin.getText();

        // Check if admin is logging in
        if (Username.equals(adminUsername) && Password.equals(adminPassword)) {
            // Navigate to Admin Page
            AdminPage adminFrame = new AdminPage(); // Create an AdminPage JFrame
            adminFrame.setVisible(true);
            adminFrame.pack();
            adminFrame.setLocationRelativeTo(null);
            this.dispose();
        } else {
            // Check for regular user in the database
            query = "SELECT * FROM user WHERE username = '" + Username + "'";
            ResultSet rs = st.executeQuery(query);
            

            while (rs.next()) {
                passDb = rs.getString("password");
                fname = rs.getString("fullname");
                emailAddress = rs.getString("email");
                conpass = rs.getString("confirm_password");
                userID = rs.getString("userID");  // Get the userID
                notFound = 1;
            }

            if (notFound == 1 && Password.equals(passDb)) {
            // Navigate to Home Page for regular user
            Home homeFrame = new Home();
            homeFrame.setUser(fname);
            homeFrame.setUser(emailAddress);
            homeFrame.setUser(conpass);
            homeFrame.setUserID(userID);  // Set the userID
            homeFrame.setVisible(true);
            homeFrame.pack();
            homeFrame.setLocationRelativeTo(null);
            this.dispose();
        } else {
                JOptionPane.showMessageDialog(new JFrame(), "Incorrect Username or password", "Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
        passlogin.setText("");
    }
} catch (Exception e) {
    System.out.println("Error: " + e.getMessage());
}

        
// TODO add your handling code here:
    }//GEN-LAST:event_loginbtnActionPerformed

    private void passloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passloginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passloginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
// /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            @Override
//            public void run() {
//                new LogIn().setVisible(true);
//            }
//        });
//    }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new LogIn().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton loginbtn;
    private javax.swing.JPasswordField passlogin;
    private javax.swing.JButton signupbtn;
    private javax.swing.JTextField unamelogin;
    // End of variables declaration//GEN-END:variables
}
