/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.SQLException;

/**
 *
 * @author jerli
 */
public class RequestField extends javax.swing.JFrame {

    Connection con;
    
    
    private String requestID;
    private String userID;

    
    public javax.swing.JTextField getRenotes() {
        return renotes;
    }

    public javax.swing.JTextField getRestatus() {
        return restatus;
    }

    public javax.swing.JTextField getRedate() {
        return redate;
    }

    public javax.swing.JTextField getCbrequest() {
        return cbrequest;
    }
    
     private ListofRequest listofRequest;

    public RequestField(ListofRequest listofRequest) {
        this.listofRequest = listofRequest;
        initComponents();
    }
    
   
    public RequestField(String userID) {
        this.userID = userID;  // Set the userID after login
        initComponents();
    }
    
     public void setUserID(String userID) {
        this.userID = userID;
    }

    // Getter method to access userID
    public String getUserID() {
        return userID;
    }
    
    
    public RequestField( String userID, String requestDate, String requestType, String notes, String status) {
    initComponents();
    this.userID = userID;

    // Set the text fields with the passed values
    getRedate().setText(requestDate);
    getCbrequest().setText(requestType);
    getRenotes().setText(notes);
    getRestatus().setText(status);
}

    /**
     * Creates new form RequestField
     */
    public RequestField() {
        initComponents();
        
        String Url, User, Pass;
        Url = "jdbc:MYSQL://localhost:3306/water";
        User = "root";
        Pass = "";
        
        try{
            con = DriverManager.getConnection(Url, User, Pass);
        }catch(Exception e){
            System.out.println("Error!" + e.getLocalizedMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        redate = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        renotes = new javax.swing.JTextField();
        restatus = new javax.swing.JTextField();
        resubmitbtn = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbrequest = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        jLabel7.setText("              DATE");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 230, 50));

        redate.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        redate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.add(redate, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 440, 40));

        jLabel4.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        jLabel4.setText("      REQUEST TYPE");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 230, 50));

        jLabel6.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        jLabel6.setText("            STATUS");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 230, 50));

        renotes.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        renotes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.add(renotes, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, 440, 40));

        restatus.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        restatus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.add(restatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 410, 440, 40));

        resubmitbtn.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        resubmitbtn.setText("SUBMIT");
        resubmitbtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        resubmitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resubmitbtnActionPerformed(evt);
            }
        });
        jPanel1.add(resubmitbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 470, 170, 50));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/back.png"))); // NOI18N
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jLabel8.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        jLabel8.setText("            NOTES");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 230, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/waterdrop3.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 420, -1, -1));

        cbrequest.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        cbrequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbrequestActionPerformed(evt);
            }
        });
        jPanel1.add(cbrequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 440, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 900, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resubmitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resubmitbtnActionPerformed

        
        
     // Get status from the JTextField
    String status = restatus.getText(); // Get status from text field

    // Ensure a status is entered
    if (status.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Please enter a status.");
        return;
    }

    // Get user ID (assuming you have a method to get the logged-in user's ID)
    String userID = getUserID();

    // Validate userID to ensure it's not null or empty
    if (userID == null || userID.isEmpty()) {
        JOptionPane.showMessageDialog(null, "User ID is not set. Please log in.");
        return;
    }

    // Database connection details
    String Url = "jdbc:mysql://localhost:3306/water";
    String User = "root";
    String Pass = "";

    try {
        // Establish connection
        Connection con = DriverManager.getConnection(Url, User, Pass);

        // Update the status for all requests of the current user (without checking current status)
        String query = "UPDATE request SET status = ? WHERE requestID = ?";
        PreparedStatement stmt = con.prepareStatement(query);
        stmt.setString(1, status);    // New status to be updated
        stmt.setString(2, userID);       // User ID for identifying the requests

        // Execute the update
        int rowsAffected = stmt.executeUpdate();

        // Check if any rows were updated
        if (rowsAffected > 0) {
            JOptionPane.showMessageDialog(null, "Request for status updated successfully!");
        } else {
            JOptionPane.showMessageDialog(null, "No requests found for this user.");
        }

    } catch (Exception e) { // Use Exception to catch all errors
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error updating status: " + e.getMessage());
    }

    }//GEN-LAST:event_resubmitbtnActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:

        RequestAdmin RequestFrame = new RequestAdmin();
        RequestFrame.setVisible(true);
        RequestFrame.pack();
        RequestFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void cbrequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbrequestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbrequestActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RequestField.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RequestField.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RequestField.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RequestField.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RequestField().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JTextField cbrequest;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField redate;
    private javax.swing.JTextField renotes;
    private javax.swing.JTextField restatus;
    private javax.swing.JButton resubmitbtn;
    // End of variables declaration//GEN-END:variables
}
