import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author jerli
 */
public class RequestAdmin extends javax.swing.JFrame {
    
    Connection con;
    
    private String userID;  // Declare userID as a field

    
   
   
   public RequestAdmin(String userID) {
        this.userID = userID;  // Set the userID after login
        initComponents();
    }
   
   
   
    

    /**
     * Creates new form RequestAdmin
     */
    public RequestAdmin() {
        initComponents();
        
        String Url, User, Pass;
        Url = "jdbc:MYSQL://localhost:3306/water";
        User = "root";
        Pass = "";
        
        try{
            con = DriverManager.getConnection(Url, User, Pass);
        }catch(Exception e){
            System.out.println("Error!" + e.getLocalizedMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        useradmin = new javax.swing.JButton();
        recordbtn = new javax.swing.JButton();
        announcementbtn = new javax.swing.JButton();
        requestbtn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbRequest = new javax.swing.JTable();
        reView = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logosmall.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        useradmin.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        useradmin.setText("Users");
        useradmin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        useradmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useradminActionPerformed(evt);
            }
        });
        jPanel1.add(useradmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, 100, 40));

        recordbtn.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        recordbtn.setText("Records");
        recordbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        recordbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recordbtnActionPerformed(evt);
            }
        });
        jPanel1.add(recordbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 30, 110, 40));

        announcementbtn.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        announcementbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/announcement.png"))); // NOI18N
        announcementbtn.setBorder(null);
        announcementbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                announcementbtnActionPerformed(evt);
            }
        });
        jPanel1.add(announcementbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 30, 50, 40));

        requestbtn.setBackground(new java.awt.Color(102, 204, 255));
        requestbtn.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        requestbtn.setText("Request");
        requestbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        requestbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestbtnActionPerformed(evt);
            }
        });
        jPanel1.add(requestbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 30, 100, 40));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logout.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 20, -1, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/waterdrop3.png"))); // NOI18N
        jLabel2.setToolTipText("");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 460, -1, -1));

        tbRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "FULLNAME"
            }
        ));
        jScrollPane1.setViewportView(tbRequest);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 860, 370));

        reView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/view.png"))); // NOI18N
        reView.setToolTipText("");
        reView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reViewActionPerformed(evt);
            }
        });
        jPanel1.add(reView, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 130, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        LogIn LoginFrame = new LogIn();
        LoginFrame.setVisible(true);
        LoginFrame.pack();
        LoginFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void announcementbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_announcementbtnActionPerformed

        Announcements AnnouncementsFrame = new Announcements();
     AnnouncementsFrame.setVisible(true);
     AnnouncementsFrame.pack();
     AnnouncementsFrame.setLocationRelativeTo(null);
     this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_announcementbtnActionPerformed

    private void recordbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recordbtnActionPerformed
        AdminRecords1 AdminRecords1Frame = new AdminRecords1();
        AdminRecords1Frame.setVisible(true);
        AdminRecords1Frame.pack();
        AdminRecords1Frame.setLocationRelativeTo(null);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_recordbtnActionPerformed

    private void useradminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useradminActionPerformed

        // TODO add your handling code here:
        AdminPage AdminPageFrame = new AdminPage();
        AdminPageFrame.setVisible(true);
        AdminPageFrame.pack();
        AdminPageFrame.setLocationRelativeTo(null);
        this.dispose();
        

    }//GEN-LAST:event_useradminActionPerformed

    private void requestbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestbtnActionPerformed
        // TODO add your handling code here:
        
        String sql = "SELECT * FROM user";
        try{
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            DefaultTableModel model = (DefaultTableModel)tbRequest.getModel();
            model.setRowCount(0);
            while(rs.next()){
                model.addRow(new String[]{rs.getString(1),rs.getString(4)} );
                
            }
        }catch(Exception e){
            System.out.println("Error!" + e.getLocalizedMessage());
        }
    }//GEN-LAST:event_requestbtnActionPerformed

    private void reViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reViewActionPerformed


        // TODO add your handling code here:
        
        int selectedRow = tbRequest.getSelectedRow();
    
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(new JFrame(), "Please select a user from the table.", 
                                      "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    // Get the selected user's data (ID, Fullname, Email, Username, Password, etc.)
    String userID = tbRequest.getValueAt(selectedRow, 0).toString(); // Assuming ID is in column 0
    String fullName = tbRequest.getValueAt(selectedRow, 1).toString(); // Full name in column 1
    
    
    
        ListofRequest ListFrame = new ListofRequest(userID, fullName);
        ListFrame.setVisible(true);
        ListFrame.pack();
        ListFrame.setLocationRelativeTo(null);
        this.dispose();
    
        
                                             
    }//GEN-LAST:event_reViewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RequestAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RequestAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RequestAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RequestAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RequestAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton announcementbtn;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton reView;
    private javax.swing.JButton recordbtn;
    private javax.swing.JButton requestbtn;
    private javax.swing.JTable tbRequest;
    private javax.swing.JButton useradmin;
    // End of variables declaration//GEN-END:variables
}
