/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.text.ParseException;


/**
 *
 * @author jerli
 */
public class RequestUser extends javax.swing.JFrame {
    Connection con;

     private String userID;  // This should come from the login authentication

    
    public RequestUser(String userID) {
        this.userID = userID;  // Set the userID after login
        initComponents();
    }
    
    public void setUserID(String userID) {
        this.userID = userID;
    }

    // Getter method to access userID
    public String getUserID() {
        return userID;
    }
    
    /**
     * Creates new form RequestUser
     */
    public RequestUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        homebtn = new javax.swing.JButton();
        recordbtn = new javax.swing.JButton();
        requestbtn = new javax.swing.JButton();
        logoutbtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        renotes = new javax.swing.JTextField();
        redate = new javax.swing.JTextField();
        resubmitbtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cbrequest = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homebtn.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        homebtn.setText("Home");
        homebtn.setBorder(new javax.swing.border.MatteBorder(null));
        homebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebtnActionPerformed(evt);
            }
        });
        jPanel1.add(homebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 100, 40));

        recordbtn.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        recordbtn.setText("Records");
        recordbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        recordbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recordbtnActionPerformed(evt);
            }
        });
        jPanel1.add(recordbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, 110, 40));

        requestbtn.setBackground(new java.awt.Color(0, 204, 255));
        requestbtn.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        requestbtn.setText("Request");
        requestbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        requestbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestbtnActionPerformed(evt);
            }
        });
        jPanel1.add(requestbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 30, 100, 40));

        logoutbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logout.png"))); // NOI18N
        logoutbtn.setBorder(null);
        logoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbtnActionPerformed(evt);
            }
        });
        jPanel1.add(logoutbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 20, 60, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logosmall.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/announcement.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 30, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/waterdrop3.png"))); // NOI18N
        jLabel2.setToolTipText("");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 440, -1, -1));

        jLabel4.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        jLabel4.setText("      REQUEST TYPE");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 230, 50));

        jLabel6.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        jLabel6.setText("            NOTES");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 230, 50));

        jLabel7.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        jLabel7.setText("              DATE");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 230, 50));

        renotes.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        renotes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.add(renotes, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 410, 440, 40));

        redate.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        redate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.add(redate, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 440, 40));

        resubmitbtn.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        resubmitbtn.setText("SUBMIT");
        resubmitbtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        resubmitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resubmitbtnActionPerformed(evt);
            }
        });
        jPanel1.add(resubmitbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 500, 170, 50));

        jButton2.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jButton2.setText("VIEW REQUEST");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 170, 130, 30));

        cbrequest.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.add(cbrequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, 440, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resubmitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resubmitbtnActionPerformed

        
                                 
    
    // Get selected request type and notes from the UI
    String requestType = cbrequest.getText(); // Get selected request type
    String notes = renotes.getText(); // Get notes from text field

    // Ensure user selected a request type and entered notes
    if (requestType.isEmpty() || notes.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Please select a request type and provide notes.");
        return;
    }

    // Validate userID to ensure it's not null or empty
    if (userID == null || userID.isEmpty()) {
        JOptionPane.showMessageDialog(null, "User ID is not set. Please log in.");
        return;
    }

    // Get the requested date from a text field (assuming 'dateInput' is the name of the field)
    String inputDate = redate.getText(); // e.g., "2020-12-01"

    // Validate if the input date is in correct format (YYYY-MM-DD)
    java.sql.Date requestDate = null;
    try {
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        java.util.Date parsedDate = dateFormat.parse(inputDate);
        requestDate = new java.sql.Date(parsedDate.getTime()); // Convert to SQL Date
    } catch (ParseException e) {
        JOptionPane.showMessageDialog(null, "Invalid date format. Please use YYYY-MM-DD.");
        return;
    }

    // Database connection details
    String Url = "jdbc:mysql://localhost:3306/water";
    String User = "root";
    String Pass = "";

    try {
        // Establish connection
        Connection con = DriverManager.getConnection(Url, User, Pass);
        String query = "INSERT INTO request (userID, request_date, request_type, notes, status) VALUES (?, ?, ?, ?, ?)";
        PreparedStatement stmt = con.prepareStatement(query);
        stmt.setString(1, userID);          // userID as a string
        stmt.setDate(2, requestDate);        // user-provided date
        stmt.setString(3, requestType);     // request type from user input
        stmt.setString(4, notes);           // Notes provided by the user
        stmt.setString(5, "Pending");       // Default status for the user

        // Execute the query
        stmt.executeUpdate();

        // Success message
        JOptionPane.showMessageDialog(null, "Request submitted successfully!");

    } catch (Exception e) { // Use Exception to catch all errors
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error submitting request: " + e.getMessage());
    }





        
    }//GEN-LAST:event_resubmitbtnActionPerformed

    private void logoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbtnActionPerformed

        LogIn LoginFrame = new LogIn();
        LoginFrame.setVisible(true);
        LoginFrame.pack();
        LoginFrame.setLocationRelativeTo(null);
        this.dispose();
        }

        public void setUser(String name){
            //        user.setText("Hi, " + name + "!");

            // TODO add your handling code here:
    }//GEN-LAST:event_logoutbtnActionPerformed

    private void requestbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestbtnActionPerformed
        // TODO add your handling code here:

        RequestUser RequestUserFrame = new RequestUser(userID);
        RequestUserFrame.setVisible(true);
        RequestUserFrame.pack();
        RequestUserFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_requestbtnActionPerformed

    private void recordbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recordbtnActionPerformed
        UserRecords RecordsFrame = new UserRecords(userID);
        RecordsFrame.setVisible(true);
        RecordsFrame.pack();
        RecordsFrame.setLocationRelativeTo(null);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_recordbtnActionPerformed

    private void homebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homebtnActionPerformed

        Home HomeFrame = new Home(userID);
        HomeFrame.setVisible(true);
        HomeFrame.pack();
        HomeFrame.setLocationRelativeTo(null);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_homebtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    UserAnnouncement UserAnnouncementFrame = new UserAnnouncement();
        UserAnnouncementFrame.setVisible(true);
        UserAnnouncementFrame.pack();
        UserAnnouncementFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
                                          
    // Database connection details
    String url = "jdbc:MYSQL://localhost:3306/water";
    String user = "root";
    String pass = "";
    Connection con = null;

    try {
        // Establish the database connection
        con = DriverManager.getConnection(url, user, pass);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Database connection failed: " + e.getLocalizedMessage());
        return; // Exit the method if the connection fails
    }

    // Replace getUserID() with loginUser
    String loginUser = getUserID(); // Assuming this fetches the logged-in user's ID

    // SQL query to filter requests by userID
    String sql = "SELECT * FROM request WHERE userID = ?";
    try {
        PreparedStatement pst = con.prepareStatement(sql);
        pst.setString(1, loginUser); // Use loginUser here
        ResultSet rs = pst.executeQuery();

        boolean recordsFound = false;

        while (rs.next()) {
            recordsFound = true;
            String userID = rs.getString("userID");
            String requestDate = rs.getString("request_date");
            String requestType = rs.getString("request_type");
            String notes = rs.getString("notes");
            String status = rs.getString("status");

            // Create and display a new RequestField frame
            AnnounceRequest AnnounceRequestFrame = new AnnounceRequest(userID, requestDate, requestType, notes, status);
            AnnounceRequestFrame.setVisible(true);
            AnnounceRequestFrame.pack();
            AnnounceRequestFrame.setLocationRelativeTo(null);
        }

        if (!recordsFound) {
            JOptionPane.showMessageDialog(null, "No requests found for userID: " + loginUser);
        }

        this.dispose(); // Dispose of the current frame
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error processing the request: " + e.getLocalizedMessage());
    } finally {
        try {
            if (con != null) {
                con.close(); // Close the connection
            }
        } catch (Exception e) {
            System.out.println("Error closing connection: " + e.getLocalizedMessage());
        }
    }

        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RequestUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RequestUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RequestUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RequestUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RequestUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cbrequest;
    private javax.swing.JButton homebtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logoutbtn;
    private javax.swing.JButton recordbtn;
    private javax.swing.JTextField redate;
    private javax.swing.JTextField renotes;
    private javax.swing.JButton requestbtn;
    private javax.swing.JButton resubmitbtn;
    // End of variables declaration//GEN-END:variables
}
