/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author jerli
 */
public class UserAnnouncement extends javax.swing.JFrame {
    Connection con;
    
    private String userID;  // Declare userID as a field
    private String fullname;
    

   
   public UserAnnouncement(String userID) {
        this.userID = userID; 
        
   }
    
  
    // Method to set userID
    public void setUserID(String userID ) {
        this.userID = userID;
        
    }

    // Getter method to access userID
    public String getUserID() {
        return userID;
    }
    
    


    /**
     * Creates new form UserAnnouncement
     */
    public UserAnnouncement() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        homebtn = new javax.swing.JButton();
        recordbtn = new javax.swing.JButton();
        requestbtn = new javax.swing.JButton();
        announcebtn = new javax.swing.JButton();
        logoutbtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        anndate = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        anncontent = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homebtn.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        homebtn.setText("Home");
        homebtn.setBorder(new javax.swing.border.MatteBorder(null));
        homebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebtnActionPerformed(evt);
            }
        });
        jPanel1.add(homebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 100, 40));

        recordbtn.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        recordbtn.setText("Records");
        recordbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        recordbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recordbtnActionPerformed(evt);
            }
        });
        jPanel1.add(recordbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, 110, 40));

        requestbtn.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        requestbtn.setText("Request");
        requestbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        requestbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestbtnActionPerformed(evt);
            }
        });
        jPanel1.add(requestbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 30, 100, 40));

        announcebtn.setBackground(new java.awt.Color(0, 204, 255));
        announcebtn.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        announcebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/announcement.png"))); // NOI18N
        announcebtn.setBorder(null);
        announcebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                announcebtnActionPerformed(evt);
            }
        });
        jPanel1.add(announcebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 30, 50, 40));

        logoutbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logout.png"))); // NOI18N
        logoutbtn.setBorder(null);
        logoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbtnActionPerformed(evt);
            }
        });
        jPanel1.add(logoutbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 20, 60, 60));

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel5.setText("      DATE");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 140, 50));

        anndate.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        anndate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(anndate, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 490, 50));

        anncontent.setColumns(20);
        anncontent.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        anncontent.setRows(5);
        anncontent.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jScrollPane1.setViewportView(anncontent);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 640, 320));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/waterdrop3.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 450, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logosmall.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homebtnActionPerformed

        Home HomeFrame = new Home(userID);
        HomeFrame.setVisible(true);
        HomeFrame.pack();
        HomeFrame.setLocationRelativeTo(null);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_homebtnActionPerformed

    private void recordbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recordbtnActionPerformed
        // TODO add your handling code here:

        UserRecords userRecordsFrame = new UserRecords(userID);  // Pass userID directly
        userRecordsFrame.setVisible(true);
        userRecordsFrame.pack();
        userRecordsFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_recordbtnActionPerformed

    private void requestbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestbtnActionPerformed
        // TODO add your handling code here:

        RequestUser RequestUserFrame = new RequestUser(userID); // Pass userID
        RequestUserFrame.setVisible(true);
        RequestUserFrame.pack();
        RequestUserFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_requestbtnActionPerformed

    private void logoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbtnActionPerformed

        LogIn LoginFrame = new LogIn();
        LoginFrame.setVisible(true);
        LoginFrame.pack();
        LoginFrame.setLocationRelativeTo(null);
        this.dispose();
        }

        public void setUser(String name){
            //        user.setText("Hi, " + name + "!");

            // TODO add your handling code here:
    }//GEN-LAST:event_logoutbtnActionPerformed

    private void announcebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_announcebtnActionPerformed

        String Url = "jdbc:mysql://localhost:3306/water";
        String User = "root";
        String Pass = "";

        // Input field variables
        String Month;

        try {
            // Load the MySQL JDBC Driver
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(Url, User, Pass);

            // Get the month input from the user (in the format YYYY-MM)
            if ("".equals(anndate.getText())) {
                JOptionPane.showMessageDialog(new JFrame(), "Month is required", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                Month = anndate.getText(); // e.g., "2024-12"

                // Query to get announcements for the given month
                String query = "SELECT * FROM announcement WHERE DATE_FORMAT(announcement_date, '%Y-%m') = ?";

                PreparedStatement pstmt = con.prepareStatement(query);
                pstmt.setString(1, Month);

                ResultSet rs = pstmt.executeQuery();

                // Check if results are found and display them
                if (rs.next()) {
                    StringBuilder sb = new StringBuilder();
                    do {
                        String title = rs.getString("title");
                        String content = rs.getString("content");
                        String date = rs.getString("announcement_date");
                        sb.append("Date: ").append(date).append("\n\n\n");
                        sb.append("Title: ").append(title).append("\n\n\n");
                        sb.append("Content: ").append(content).append("\n\n\n");
                    } while (rs.next());

                    // Display the result in the JTextArea
                    anncontent.setText(sb.toString()); // Display announcements in the content textarea
                } else {
                    JOptionPane.showMessageDialog(null, "No announcements found for this month.", "No Data", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        } catch (Exception e) {
            System.out.println("Error! " + e.getLocalizedMessage());
            JOptionPane.showMessageDialog(new JFrame(), "Error: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_announcebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserAnnouncement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserAnnouncement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserAnnouncement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserAnnouncement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserAnnouncement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea anncontent;
    private javax.swing.JTextField anndate;
    private javax.swing.JButton announcebtn;
    private javax.swing.JButton homebtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logoutbtn;
    private javax.swing.JButton recordbtn;
    private javax.swing.JButton requestbtn;
    // End of variables declaration//GEN-END:variables
}
