/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author jerli
 */
public class UserRecords extends javax.swing.JFrame {

  
    
    private String userID;  // This should come from the login authentication

    
    public UserRecords(String userID) {
        this.userID = userID;  // Set the userID after login
        initComponents();
    }
    
    public void setUserID(String userID) {
        this.userID = userID;
    }

    // Getter method to access userID
    public String getUserID() {
        return userID;
    }
    
    
    
    
    /**
     * Creates new form Records
     */
    public UserRecords() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        logoutbtn = new javax.swing.JButton();
        homebtn = new javax.swing.JButton();
        recordbtn = new javax.swing.JButton();
        requestbtn = new javax.swing.JButton();
        announcebtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbUserRecord = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logosmall.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/waterdrop3.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 430, -1, -1));

        logoutbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logout.png"))); // NOI18N
        logoutbtn.setBorder(null);
        logoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbtnActionPerformed(evt);
            }
        });
        jPanel1.add(logoutbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 30, -1, -1));

        homebtn.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        homebtn.setText("Home");
        homebtn.setBorder(new javax.swing.border.MatteBorder(null));
        homebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebtnActionPerformed(evt);
            }
        });
        jPanel1.add(homebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, 100, 40));

        recordbtn.setBackground(new java.awt.Color(102, 204, 255));
        recordbtn.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        recordbtn.setText("Records");
        recordbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        recordbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recordbtnActionPerformed(evt);
            }
        });
        jPanel1.add(recordbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 40, 110, 40));

        requestbtn.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        requestbtn.setText("Request");
        requestbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        requestbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestbtnActionPerformed(evt);
            }
        });
        jPanel1.add(requestbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 40, 100, 40));

        announcebtn.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        announcebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/announcement.png"))); // NOI18N
        announcebtn.setBorder(null);
        announcebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                announcebtnActionPerformed(evt);
            }
        });
        jPanel1.add(announcebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 40, 50, 40));

        tbUserRecord.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "DATE", "CUBIC", "AMOUNT", "BALANCE", "TOTAL AMONT", "REMARKS"
            }
        ));
        jScrollPane1.setViewportView(tbUserRecord);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 860, 500));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, -4, 1040, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbtnActionPerformed
        LogIn LoginFrame = new LogIn();
        LoginFrame.setVisible(true);
        LoginFrame.pack();
        LoginFrame.setLocationRelativeTo(null); 
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_logoutbtnActionPerformed

    private void homebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homebtnActionPerformed

        Home HomeFrame = new Home(userID);
        HomeFrame.setVisible(true);
        HomeFrame.pack();
        HomeFrame.setLocationRelativeTo(null);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_homebtnActionPerformed

    private void recordbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recordbtnActionPerformed
        // TODO add your handling code here:

    String Url = "jdbc:mysql://localhost:3306/water";  
    String User = "root";
    String Pass = "";

    try {
        // Load the MySQL JDBC Driver
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con = DriverManager.getConnection(Url, User, Pass);

        // Query to retrieve user records based on userID
        String query = "SELECT date, cubic, amount, balance, total_amount, remarks FROM record WHERE userID = ?";
        PreparedStatement pstmt = con.prepareStatement(query);
        pstmt.setString(1, userID);  // Use the userID passed from Home or LogIn

        ResultSet rs = pstmt.executeQuery();

        // Clear the table before adding new data
        DefaultTableModel model = (DefaultTableModel) tbUserRecord.getModel();
        model.setRowCount(0);

        // Check if any records are found
        boolean recordsFound = false;

        // Populate the table with the retrieved data
        while (rs.next()) {
            String date = rs.getString("date");
            int cubic = rs.getInt("cubic");
            double balance = rs.getDouble("balance");
            double amount = rs.getDouble("amount");
            double totalAmount = rs.getDouble("total_amount");
            String remarks = rs.getString("remarks");

            model.addRow(new Object[]{date, cubic, balance, amount, totalAmount, remarks});
            recordsFound = true;  // Set to true when data is found
        }

        // If no records were found, show an error message
        if (!recordsFound) {
            JOptionPane.showMessageDialog(new JFrame(), "No records found for the user: " + userID, "No Data Found", JOptionPane.ERROR_MESSAGE);
        }

        rs.close();
        pstmt.close();
        con.close();
    } catch (Exception e) {
        System.out.println("Error! " + e.getLocalizedMessage());
        JOptionPane.showMessageDialog(new JFrame(), "Error: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
    }                     
    


 
    }//GEN-LAST:event_recordbtnActionPerformed

    private void announcebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_announcebtnActionPerformed
     UserAnnouncement UserAnnouncementFrame = new UserAnnouncement();
        UserAnnouncementFrame.setVisible(true);
        UserAnnouncementFrame.pack();
        UserAnnouncementFrame.setLocationRelativeTo(null);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_announcebtnActionPerformed

    private void requestbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestbtnActionPerformed
        // TODO add your handling code here:
        
        RequestUser RequestUserFrame = new RequestUser(userID);
        RequestUserFrame.setVisible(true);
        RequestUserFrame.pack();
        RequestUserFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_requestbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserRecords().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton announcebtn;
    private javax.swing.JButton homebtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logoutbtn;
    private javax.swing.JButton recordbtn;
    private javax.swing.JButton requestbtn;
    private javax.swing.JTable tbUserRecord;
    // End of variables declaration//GEN-END:variables
}
